name:                pymutint
version:             0.1.0.0
github:              "gdevanla/pymutint"
license:             BSD3
author:              "Guru Devanla"
maintainer:          "grdvnl@gmail.com"
copyright:           "2019 Guru Devanla"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Mutant generation library for the Python language.
category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gdevanla/pymutint#readme>

dependencies:
- base >= 4.7 && < 5
- language-python
- containers
- vector

library:
  source-dirs: src

executables:
  pymutint-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pymutint

tests:
  pymutint-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pymutint
    - tasty
    - tasty-hunit
    - tasty-quickcheck
